[[section-system-scope-and-context]]

== 3. System Scope and Context

=== 3.1 Business Context

[plantuml, "Business Context", svg]
----
actor player
Component wiq
Component wikidata

player -right-> wiq: plays
wiq <-right-> wikidata: queries
----

[cols="1,2" options="header"]
|===
| Name | Description
| Player | The user who plays the game.
| Wiq | The application is used by players and interacts with Wikidata to automatically generate questions.
| Wikidata | Collaborative database of free knowledge that stores structured data (https://www.wikidata.org/).
|===

=== 3.2 Technical Context

[plantuml, "Technical Context", svg]
----
left to right direction

actor user
component web as "webApp" { 
  rectangle front as "Frontend"
  component "Services"  {
    rectangle gw as "Gateway"
    rectangle userserv as "User service"
    rectangle authserv as "Authentication service"
    rectangle statsserv as "Statistic service"
    rectangle questionserv as "Question service"
  }
database mongo as "MongDB"      
}
Component wikidata

user <--> front: interact
front <--> gw: interact

gw <--> userserv: register
gw <--> authserv: login
gw <--> statsserv: generate stats
gw <--> questionserv: generate questions

userserv <--> mongo: read/write
authserv <--> mongo: read/write
statsserv <--> mongo: read/write
questionserv <--> mongo: read/write
questionserv <-l-> wikidata: query

userserv -[hidden]l- authserv
authserv -[hidden]l- statsserv
statsserv -[hidden]l- questionserv
----

[cols="1,2" options="header"]
|===
| Name | Description
| User 
| The user who plays the game.
| WebApp 
| The application is used by players and interacts with Wikidata to automatically generate questions.
| Frontend
| The user interface of the application.
| Gateway
| The entry point of the application.
| User service
| Manages user registration.
| Authentication service
| Manages user authentication.
| Statistic service
| Manages game statistics.
| Question service
| Handles the generation and formulation of game questions.
| MongoDB
| Database used to store the data of the application.
| Wikidata 
| Collaborative database of free knowledge that stores structured data (https://www.wikidata.org/).
|===
