[[section-runtime-view]]

== Runtime View

=== User Registration

User registration in the application is managed through the user microservice (userservice). The user enters a username and password, and if the user is created successfully, a confirmation message is displayed. Otherwise, an error message is shown.

[plantuml, "user_registration", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant userserv as "user serv"
participant mongo as "MongoDB"

user --> webapp: fill registration form
webapp -> gw: post request
gw -> userserv: post request
userserv -> mongo: create user
mongo -> userserv: 200
userserv -> gw: 200
gw -> webapp: 200
webapp --> user: confirmation message

----

=== Login

The application's login is managed through the authentication microservice (authservice). The user enters their credentials, and if the information is correct, a view of the application with the available options is displayed.

[plantuml, "login", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant authserv as "auth serv"
participant mongo as "MongoDB"

user --> webapp: enter credentials
webapp -> gw: get request
gw -> authserv: get request
authserv -> mongo: find user
mongo -> authserv: 200
authserv -> gw: 200
gw -> webapp: 200
webapp --> user: confirmation message
----

=== Play

The quiz game is managed through the authentication microservice (questionservice). The user starts a new game, and a new question with its corresponding answers is displayed.

[plantuml, "play", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant qserv as "question serv"
participant mongo as "MongoDB"

user --> webapp: start game
webapp -> gw: get request
gw -> qserv: get request
qserv -> mongo: find question
mongo -> qserv: 200
qserv -> gw: 200
gw -> webapp: 200
webapp --> user: ask question
user --> webapp: answer question
webapp --> user: give feedback
----

=== Statistics

The application's statistics module is handled by the statistics microservice (statsservice). Upon user request, the game statistics are presented in a view.

[plantuml, "stats", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant statsserv as "stats serv"
participant mongo as "MongoDB"

user --> webapp: enter stats page
webapp -> gw: get request
gw -> statsserv: get request
statsserv -> mongo: get stats
mongo -> statsserv: 200
statsserv -> gw: 200
gw -> webapp: 200
webapp --> user: show stats view
----
