[[section-runtime-view]]

== 6. Runtime View

=== 6.1 User Registration

User registration in the application is managed through the user microservice (userservice). The user enters a username and password, and if the user is created successfully, a confirmation message is displayed. Otherwise, an error message is shown.

[plantuml, "User registration", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant userserv as "user serv"
participant mongo as "MongoDB"

user -> webapp: fill registration form
webapp -> gw: post request
gw -> userserv: post request
userserv -> mongo: create user
mongo -> userserv: 200
userserv -> gw: 200
gw -> webapp: 200
webapp --> user: confirmation message

----

=== 6.2 Login

The application's login is managed through the authentication microservice (authservice). The user enters their credentials, and if the information is correct, a view of the application with the available options is displayed.

[plantuml, "Login", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant userserv as "user serv"
participant mongo as "MongoDB"

user -> webapp: enter credentials
webapp -> gw: get request
gw -> userserv: get request
userserv -> mongo: find user
mongo -> userserv: 200
userserv -> gw: 200
gw -> webapp: 200
webapp --> user: confirmation message
----

=== 6.3 Play

The quiz game is managed through the authentication microservice (questionservice). The user starts a new game, and a new question with its corresponding answers is displayed.

[plantuml, "Play", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant qserv as "question serv"
participant mongo as "MongoDB"

user -> webapp: start game
webapp -> gw: get request
gw -> qserv: get request
qserv -> mongo: find question
mongo -> qserv: 200
qserv -> gw: 200
gw -> webapp: 200
webapp --> user: asks question
user -> webapp: answers question
webapp --> user: gives feedback
----

=== 6.4 Statistics

The application's statistics module is handled by the statistics microservice (statsservice). Upon user request, the game statistics are presented in a view.

[plantuml, "Login", svg]
----
actor user
participant webapp as "webApp"
participant gw as "gateway"
participant statsserv as "stats serv"
participant mongo as "MongoDB"

user -> webapp: enter stats page
webapp -> gw: get request
gw -> statsserv: get request
statsserv -> mongo: get stats
mongo -> statsserv: 200
statsserv -> gw: 200
gw -> webapp: 200
webapp --> user: shows stats view
----
