[[section-concepts]]

== Cross-cutting Concepts
This section describes overall, principal regulations and solution ideas that are relevant in multiple parts (= cross-cutting) of the system.

=== Domain concepts
**- Domain model**: The domain model, including the key classes and their most important attributes, is illustrated in the following diagram.

[plantuml, "domain_model", svg]
----
!define rectangle class

rectangle User {
    +userId: String
    +name: String
    +email: String
    +passwordHash: String
}

rectangle Game {
    +gameId: String
    +userId: String
    +startTime: Date
    +endTime: Date
    +score: Int
}

rectangle Question {
    +questionId: String
    +text: String
    +options: List
    +correctAnswer: String
}

rectangle Statistic {
    +statId: String
    +userId: String
    +totalGames: Int
    +totalScore: Int
    +averageScore: Float
}

User "1" -- "0..*" Game : participates in
User "1" -- "0..*" Statistic : has
Game "1" -- "0..*" Question : includes
Game "1" -- "0..1" Statistic : generates
----

=== User Experience Concepts (UX)

**- Usability tests**: Usability tests will be conducted to ensure a pleasant user experience.

=== Safety and Security Concepts

**- Password Hashing**: During the registration process, user passwords will be hashed using a secure algorithm on the frontend before being sent and stored in the database.
Later, during the login process, passwords are retrieved hashed from the database and decrypted on the frontend.

=== Architecture and Design Patterns

**- Microservices**: The system will be designed as a set of microservices, each responsible for a specific domain or functionality.

=== "Under-the-hood"

**- Persistency**: The system will use a nosql database (Mongo DB) to store data.

**- Transaction handling**: (todo)

**- Session handling**: The system will use JWT tokens for session handling.

**- Exception and error handling**: A server-side validation layer will be develop to catch and handle exceptions and errors effectively.


=== Development Concepts

**- CI/CD**: The system will be developed using GitHub Actions for continuous integration and continuous deployment (CI/CD).

=== Operational Concepts
**- Administration**: The system will provide an administration interface to manage users, roles, and other system settings.

**- Scalability**: The system will be deployed on an Azure virtual machine, which allows for easy scaling.

**- Monitoring**: The system will be monitored using Prometheus and Grafana. Prometheus is an open-source monitoring and alerting toolkit. Grafana is a visualization tool that allows you to create dashboards and graphs.

